Repository iScsc/blog.iscsc.fr, pull requests merged in 2024-05, with the labels that each got.

#53 Introduce a new subdomain dev.iscsc.fr to publish in-development features from opened PRs
  .github/workflows/build_and_deploy.yml
  README.md
  docker-compose.yml
  nginx.conf
Labels: enhancement

#61 Add deploy to `dev.iscsc.fr` workflow
  .github/workflows/deploy_dev.yml
  development_banner.html
  docker-compose.dev.yml
Labels: tooling

#51 Update deprecated http2 nginx conf syntax
  nginx.conf
Labels: maintenance

#50 Remove deprecated `version` in docker-compose.yml
  docker-compose.yml
Labels: maintenance

#28 Add files via upload (docker volume article)
  src/content/posts/docker_bind_mounts_introduction.md
Labels: new post
